AWSTemplateFormatVersion: '2010-09-09'
Description: Rôles IAM pour CodeBuild et CodePipeline

Resources:

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codebuild-immoloc-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codepipeline-immoloc-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - iam:PassRole
                Resource: "*"

Outputs:
  CodeBuildRoleArn:
    Value: !GetAtt CodeBuildRole.Arn
  CodePipelineRoleArn:
    Value: !GetAtt CodePipelineRole.Arn
